spring:
  application:
    name: clean_alba_backend
kakao:
  client-id: "fedb5f9d642224f6cd5c42bc29ba0f84"
  client-secret: "gYJ2qGwzitLmo1jzRKHdf6bYd7IBdc28"
  redirect-url: "http://localhost:5173/kakao/auth-code"
jwt:
  secret: "clean-alba-secret-key-please-change-this-in-production-must-be-long"
  expiration-ms: 86400000